export enum NotificationType {
  BILLING_CYCLE = 'BILLING_CYCLE',
  PAYMENT_DUE = 'PAYMENT_DUE',
  PAYMENT_SUBMITTED = 'PAYMENT_SUBMITTED',
  PAYMENT_VERIFIED = 'PAYMENT_VERIFIED',
  PAYMENT_REJECTED = 'PAYMENT_REJECTED',
  SERVICE_DISCONNECTED = 'SERVICE_DISCONNECTED',
  SERVICE_RECONNECTED = 'SERVICE_RECONNECTED',
  OUTAGE_ALERT = 'OUTAGE_ALERT',
  SYSTEM = 'SYSTEM',
  CUSTOM = 'CUSTOM',
  // Partner notification types
  DISTRIBUTION_AVAILABLE = 'DISTRIBUTION_AVAILABLE',
  MONTHLY_SUMMARY = 'MONTHLY_SUMMARY',
  PARTNER_WELCOME = 'PARTNER_WELCOME',
  EARNINGS_ALERT = 'EARNINGS_ALERT',
  PARTNERSHIP_STATUS_CHANGE = 'PARTNERSHIP_STATUS_CHANGE',
}

export enum NotificationChannel {
  IN_APP = 'IN_APP',
  SMS = 'SMS',
  EMAIL = 'EMAIL',
  PUSH = 'PUSH',
}

export enum NotificationStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  FAILED = 'FAILED',
  READ = 'READ',
}
