/**
 * Equipment Cost Analysis Types
 * 
 * Types for tracking equipment expenses, depreciation, and ROI calculations
 */

// Equipment cost update input
export interface EquipmentCostInput {
  purchaseCost?: number;
  monthlyDepreciation?: number;
  maintenanceCost?: number;
}

// Equipment financial summary
export interface EquipmentFinancials {
  totalEquipmentCost: number;      // Sum of all equipment purchase costs
  monthlyDepreciation: number;     // Total monthly depreciation
  maintenanceCosts: number;        // Total maintenance expenses
  equipmentROI: number;            // Average ROI across all equipment
  costPerCustomer: number;         // Equipment cost per active customer
  equipmentCount: number;          // Total number of equipment items
}

// Individual equipment ROI calculation
export interface EquipmentROI {
  equipmentId: string;
  equipmentName: string;
  totalCost: number;               // Purchase cost + maintenance
  totalRevenue: number;            // Revenue generated by this equipment
  netProfit: number;               // Revenue - costs
  roiPercentage: number;           // (profit / cost) * 100
  paybackMonths: number;           // Months to recover investment
  monthsInService: number;         // How long equipment has been in use
  isAssigned: boolean;             // Whether equipment is currently assigned
  assignedCustomerCount: number;   // Number of customers using this equipment
}

// Equipment cost analysis for date range
export interface EquipmentCostAnalysis {
  dateRange: {
    startDate: Date;
    endDate: Date;
  };
  totalCosts: {
    purchase: number;
    maintenance: number;
    depreciation: number;
    total: number;
  };
  revenueGenerated: number;
  netProfit: number;
  averageROI: number;
  equipmentBreakdown: EquipmentROI[];
  monthlyTrend: MonthlyEquipmentCost[];
}

// Monthly equipment cost breakdown
export interface MonthlyEquipmentCost {
  month: string;                   // YYYY-MM format
  depreciation: number;
  maintenance: number;
  newPurchases: number;
  totalCost: number;
  revenue: number;
  profit: number;
}

// Maintenance record
export interface MaintenanceRecord {
  id: string;
  equipmentId: string;
  maintenanceDate: Date;
  cost: number;
  description: string;
  performedBy: string;             // User ID who performed maintenance
  createdAt: Date;
  updatedAt: Date;
}

// Maintenance record input
export interface CreateMaintenanceRecordInput {
  equipmentId: string;
  maintenanceDate: Date;
  cost: number;
  description: string;
}

// Equipment cost filters
export interface EquipmentCostFilters {
  showOnlyWithCosts?: boolean;
  minROI?: number;
  maxROI?: number;
  hasMaintenanceRecords?: boolean;
  dateRange?: {
    startDate: Date;
    endDate: Date;
  };
}

// Date range utility type
export interface DateRange {
  startDate: Date;
  endDate: Date;
}

// Equipment cost breakdown for analytics
export interface EquipmentCostBreakdown {
  month: string;
  totalEquipment: number;
  costs: {
    depreciation: number;
    maintenance: number;
    total: number;
  };
  revenue: {
    equipmentGenerated: number;  // Revenue from equipment-assigned customers
    totalRevenue: number;
  };
  efficiency: {
    costPerCustomer: number;
    revenuePerEquipment: number;
    utilizationRate: number;     // Percentage of equipment assigned
  };
  equipmentDetails: Array<{
    equipmentId: string;
    name: string;
    cost: number;
    revenue: number;
    roi: number;
  }>;
}

// ROI performance categories
export enum ROIPerformanceCategory {
  EXCELLENT = 'EXCELLENT',     // ROI > 50%
  GOOD = 'GOOD',               // ROI 20-50%
  AVERAGE = 'AVERAGE',         // ROI 5-20%
  POOR = 'POOR',               // ROI 0-5%
  NEGATIVE = 'NEGATIVE',       // ROI < 0%
}

// Equipment ROI comparison
export interface EquipmentROIComparison {
  equipmentId: string;
  equipmentName: string;
  currentROI: number;
  previousROI: number;
  roiChange: number;           // Percentage change
  performanceCategory: ROIPerformanceCategory;
  trend: 'IMPROVING' | 'DECLINING' | 'STABLE';
}

// Maintenance cost summary
export interface MaintenanceCostSummary {
  equipmentId: string;
  equipmentName: string;
  totalMaintenanceCost: number;
  maintenanceCount: number;
  averageCostPerMaintenance: number;
  lastMaintenanceDate: Date | null;
  nextScheduledMaintenance: Date | null;
  maintenanceFrequency: number; // Days between maintenance
}

// Equipment depreciation schedule
export interface DepreciationSchedule {
  equipmentId: string;
  equipmentName: string;
  purchaseCost: number;
  monthlyDepreciation: number;
  totalDepreciated: number;
  remainingValue: number;
  depreciationRate: number;     // Percentage per month
  estimatedLifespan: number;    // Months until fully depreciated
}